"""Add is_admin to Tenant

Revision ID: c061f32ba806
Revises: 20260101_whatsapp
Create Date: 2026-01-01 14:46:05.444819+05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c061f32ba806'
down_revision: Union[str, None] = '20260101_whatsapp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_admin')
    # ### end Alembic commands ###
